[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
repo  = 'Shougo/context_filetype.vim'
on_ft = ['toml']


[[plugins]]
repo    = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_ft   = ['toml']
